Grid layout 1
js-tasks-ru/htmlcss-20210513_mkhd pull request #10
Opened 2021-05-27 05:49 UTC by MakhmudAliev

2021-05-27 05:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 10:03 UTC, GSemikozov requested changes

2021-05-30 10:03 UTC, GSemikozov commented on components/grid_layout/grid_layout.css
> +.page {
в данном файле собраны все блоки темплейта - надо бы разнести их по компонентам, как мы это делали в случае с Главной. В данном случае, можем сделать так: все компоненты темплейта будем размещать здесь (`components/grid_layout/main/main.css` и т.д.), а стили подключать так: 
```
components/grid_layout/grid_layout.css
...
@import "./main/main.css";
```

2021-05-30 10:03 UTC, GSemikozov commented on components/grid_layout/grid_layout.css
> +.page {
кроме того, хедер у нас уже сверстан - так что мы можем следовать подходу переиспользования компонентов. В темплейте хедер отличается от хедера на Главной тем, что присутствует только верхняя панель + цвет фона меняем через класс-модификатор.

2021-05-30 10:03 UTC, GSemikozov commented on components/grid_layout/grid_layout.css
> +  height: 100px;
фиксировать высоту хедера и футера не обязательно, все и так будет хорошо, поскольку у родителя мы 
указали что это будет auto - grid-template-rows: auto 1fr auto;

2021-05-30 10:03 UTC, GSemikozov commented on components/grid_layout/grid_layout.css
> +  background: red;
кстати! цвет фона и все прочие параметры берем именно из дизайна, а не из той версии которую я показал на занятии))

2021-05-30 17:42 UTC, MakhmudAliev commented on components/grid_layout/grid_layout.css
> +.page {
переделал подключение стилей - создал подпапок для каждого блока

2021-05-30 17:43 UTC, MakhmudAliev commented on components/grid_layout/grid_layout.css
> +  height: 100px;
где же тогда указывается высота хедера?

2021-05-30 17:43 UTC, MakhmudAliev commented on components/grid_layout/grid_layout.css
> +  background: red;
понял - затупил, сейчас переделал

2021-05-30 19:18 UTC, GSemikozov commented on components/grid_layout/grid_layout.css
> +  height: 100px;
а ее не обязательно фиксировать - она будет высчитываться автоматом в зависимости от своего внутреннего содержимого

2021-06-05 11:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-05 11:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-05 18:37 UTC, GSemikozov approved these changes

2021-06-05 18:37 UTC, merged