Histogram
js-tasks-ru/htmlcss-20210513_mkhd pull request #8
Opened 2021-05-24 13:56 UTC by MakhmudAliev

.histogram__view-all a { - стоит так делать или класс лучше навешать на ссылку?

Стили связанные с line-height решил вынести в глобальный файл - у заголовков 1.1, у обычного текста - 1.6 вроде так делают, что скажешь?

view all находится чуууть ниже чем total orders - это специально так? добавить марджин-топ у блока со ссылкой на пару пикселей?

2021-05-24 13:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 22:16 UTC, GSemikozov commented
> .histogram__view-all a { - стоит так делать или класс лучше навешать на ссылку?
> 
> Стили связанные с line-height решил вынести в глобальный файл - у заголовков 1.1, у обычного текста - 1.6 вроде так делают, что скажешь?
> 
> view all находится чуууть ниже чем total orders - это специально так? добавить марджин-топ у блока со ссылкой на пару пикселей?

1. лучше класс
2. это ок, так тоже делают, да
3. достаточно выравнивать детей контейнера по вертикали, не нужно отступ у ссылки

2021-05-26 22:19 UTC, GSemikozov requested changes

2021-05-26 22:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 354px;
фиксированные размеры убираем)

2021-05-26 22:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all a {
по этому поводу написал в общем комментарии

2021-05-26 22:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  color: #4263eb;
цвет если есть лучше взять из переменных

2021-05-26 22:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 9px;
ширину в 9px можно задать как минимально допустимую, а вот сам __bar лучше сделать адаптивный -  пусть все колонки тянутся по родителю (напомню про коэффициент жадности)

2021-05-26 22:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  background-color: #4263eb;
цвет возьмем из переменных

2021-05-26 22:19 UTC, GSemikozov commented on assets/css/main.css
> +  line-height: 1.6;
вот тут все-таки некорректно - вместо body лучше задать на p

2021-05-30 09:10 UTC, MakhmudAliev commented on assets/css/main.css
> +  line-height: 1.6;
сделал

2021-05-30 09:10 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +  color: #4263eb;
ок

2021-05-30 09:10 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all a {
ок

2021-05-30 09:10 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +  width: 354px;
убрал, этот момент понял

2021-05-30 09:10 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +  width: 9px;
переделал

2021-05-30 09:55 UTC, GSemikozov requested changes

2021-05-30 09:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 50%;
если задавать высоту родителя в процентах, то она будет увеличиваться / уменьшаться в взависимости от высоты родителя. Это ок. Но - колонки этого элемента заданы в пикселях - поэтому как бы ни увеличивался / ни уменьшался наш элемент, колонки всегда будет иметь одну и ту же высоту) Поэтому - здесь стоит сделать наоборот - зафиксировать высоту контейнера для колонок (на самом деле, не обязательно, но так мы договорились на занятии), а высоту самих колонок - задавать в процентах.

2021-05-30 16:07 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +  height: 50%;
смотрел занятие вроде внимательно... поставил height: 80px; - так?

2021-05-30 19:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 50%;
там на самом. деле 50px, но и 80 будет ок - я не придираюсь к пиксель-перфект верстке, главное - понять принцип)

2021-05-31 03:44 UTC, MakhmudAliev commented on 04-lection2/01-histogram/histogram.css
> +  height: 50%;
поправил

2021-06-01 10:08 UTC, GSemikozov approved these changes

2021-06-01 10:08 UTC, merged