Skeleton
js-tasks-ru/htmlcss-20210513_mkhd pull request #9
Opened 2021-05-24 14:08 UTC by MakhmudAliev

2021-05-26 22:24 UTC, GSemikozov requested changes

2021-05-26 22:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/README.md
> +# Скелетон
это системный файл, его нужно убрать из ПР

2021-05-26 22:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
фиксированные размеры убираем)

2021-05-26 22:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
тут и ниже - лучше задать в процентах, тогда при ресайзе блока все будет пропорционально уменьшаться / увеличиваться

2021-05-26 22:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  margin-bottom: 8px;
так у всех линий будет отступ снизу, но - он не всегда нужен (если у нас одна линия или группа линий - у последней линии не должно быть отступа)

2021-05-26 22:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/test/solution.test.js
> +const expect = require('chai').expect;
это системный файл, его надо убрать из ПР

2021-05-27 03:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-27 04:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-27 04:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 09:11 UTC, MakhmudAliev commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
убрал

2021-05-30 09:11 UTC, MakhmudAliev commented on 04-lection2/02-skeleton/skeleton.css
> +  margin-bottom: 8px;
добавил стиль для последнего элемента

2021-05-30 09:11 UTC, MakhmudAliev commented on 04-lection2/02-skeleton/test/solution.test.js
> +const expect = require('chai').expect;
ок

2021-05-30 17:41 UTC, MakhmudAliev commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
внес коррективы вроде уже давно)

2021-05-30 19:17 UTC, GSemikozov approved these changes

2021-05-30 19:17 UTC, merged